default: # default connection
  type: "sqlite"
  host: "localhost"
  port: 3306
  database: "tsnode"
  synchronize: true
  logging: false
  entities: ["src/entity/**/*.ts"]
  migrations: ["src/migration/**/*.ts"]
  subscribers: ["src/subscriber/**/*.ts"]
  cli:
    entitiesDir: "src/entity"
    migrationsDir: "src/migration"
    subscribersDir: "src/subscriber"
